sudo: required
services:
  - docker

before_install:
  - docker build -t amachi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run amachi/react-test npm test -- --coverage

after_success:
  - docker build -t amachi/multi-client ./client
  - docker build -t amachi/multi-nginx ./nginx
  - docker build -t amachi/multi-server ./server
  - docker build -t amachi/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push amachi/multi-client
  - docker push amachi/multi-nginx
  - docker push amachi/multi-server
  - docker push amachi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-747963595566
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY