sudo: required
services:
  - docker

before_install:
  - docker build -t amachi0/react-test -f ./client/Dockerfile.dev ./

script:
  - docker run amachi0/react-test npm test -- --coverage

after_success:
  - docker build -t amachi0/multi-client ./client
  - docker build -t amachi0/multi-nginx ./nginx
  - docker build -t amachi0/multi-server ./server
  - docker build -t amachi0/multi-worker ./worker